- name: Create Ec2 Instance
  hosts: localhost
  ec2:
    key_name: "{{ key }}"
    instance_tags: {Name: "{{ name }}"}
    group_id: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    image: "{{ image }}"
    wait: yes
    count: 1
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: yes
  register: ec2