---
- hosts: all
  gather_facts: false

  vars:
    aws:
      access_key: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
      secret_key: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'

  tasks:
    - name: Printing AWS credential informations
      debug:
        msg: "{{ aws.access_key }}, {{ aws.secret_key }}"

