---
- hosts: all
  gather_facts: false

  vars:
    aws:
      access_key: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
      secret_key: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'

  tasks:
    - name: Printing all the environment variables in Ansible`
      debug:
        msg: "{{ ansible_env }}"

    - name: Printing AWS credential informations
      debug:
        msg: "{{ aws }}"