---
- hosts: all
  gather_facts: true
  tasks:
    - name: Printing all the environment variables in Ansible`
      debug:
        msg: "{{ ansible_env }}"

    - name: Printing all the environment variabes
      debug:
        msg: "{{ env }}"