---
- name: Create new EC2 instances
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Launch Instance
      local_action:
        module: ec2
        key_name: "{{ key }}"
        group_id: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        region: "{{ region }}"
        image: "{{ image }}"
        wait: yes
        count: 1
        vpc_subnet_id: "{{ subnet }}"
        instance_tags: {Name: "{{ name }}"}
        assign_public_ip: yes
      register: ec2

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    - name: Instance info
      debug:
        msg: "{{ item.id }} {{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"