---
- name: Create new EC2 instances
  hosts: all
  gather_facts: true
  connection: local

  tasks:
    - name: Launch Instance
      local_action:
        module: ec2
        aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY }}"
        key_name: "{{ key }}"
        instance_type: "{{ instance_type }}"
        region: "{{ region }}"
        image: "{{ image }}"
        wait: yes
        count: 1
        vpc_subnet_id: "{{ subnet }}"
        instance_tags: {Name: "{{ instance_name }}"}
        assign_public_ip: yes
      register: ec2

    - name: Info public DNS name
      debug:
        msg: "{{ item.public_dns_name }}"
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 180
        state: started
      with_items: "{{ ec2.instances }}"

    - name: Instance info
      debug:
        msg: "{{ item.id }} {{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"